### PR TITLE
create folders for topic-hierarchy

### PR DESCRIPTION
**Pull request by amilan17**
@tomkralidis @golfvert @efucile -- What do you think about organizing the topic-hierarchy into folders?

### CODE REVIEW

**Comment by antje-s** [comment]
Maybe we could merge the csv files into one json. Then the hierarchy would be directly visible and it would be readable for both humans and machines. But that's just thinking out loud, as I don't know what the reasons for the csv variant were.

**Comment by tomkralidis** [comment]
IMO the CSVs are more manageble for as part of updates by TT-WISMD and the various communities.  But JSON is of clear value for software integration/workflow.

FYI a GitHub Action has been created that uses pywcmp to create a JSON bundle of all CSVs on repository updates to the `gh-pages` branch made available at https://wmo-im.github.io/wis2-topic-hierarchy

Regarding folder structure, perhaps we can have levels 1-8 as they are now (at the root of the repository) and then have each subdomain (level 9) with its own folder, thus have a clearer delineation from the management of core and community components?

**Comment by amilan17** [comment]
> Regarding folder structure, perhaps we can have levels 1-8 as they are now (at the root of the repository) and then have each subdomain (level 9) with its own folder, thus have a clearer delineation from the management of core and community components?

@tomkralidis I like this suggestion

**Comment by alexandreleroux** [comment]
At the TT-NWPMD meeting this morning with @amilan17 @sebvi and colleagues, we thought using GitHub folders for topic-hierarchy would make lots of sense by enabling simple and valuable hierarchical navigation.

Example for the weather domain, we'd get GitHub folder for level 9 and beyond: `/weather/prediction/[forecast, analysis, reanalysis, hindcast]/[level-11 controlled vocabulary]/[level-12 controlled vocabulary]/[level-13 controlled vocabulary]`

* We could still have the `Name` and `Description` in a csv in the corresponding folders (no need for the `Child` value anymore, given that's implicit in the folder hierarchy)
* we could add `readme.md` files which are automatically shown by Github when browsing GitHub folders. These readme could provide context, justifications and references
* using such a folder structure would avoid collisions (TT-NWPMD members mentioned the potential collision of reanalysis.csv available in multiple domains)

I'm fine with such a folder hierarchy is used only starting at level 9 (subdomains). Thanks for considering!

**Comment by josusky** [comment]
@tomkralidis I have checked the JSON bundle at https://wmo-im.github.io/wis2-topic-hierarchy/ and I think there is an error. All 3 defined centres are combined with all countries so there is `"origin/a/wis2/can/eccc-msc/data/core/weather/surface-based-observations` but also `origin/a/wis2/svk/eccc-msc/data/core/weather/*` and many many others. I don't think this is what you wanted to create.

**Comment by tomkralidis** [comment]
We have to consider the publication process and runtime workflow, given GitHub is used as a working area and the runtime target is (currently) codes.wmo.int.  We will also need a bundle for runtime functionality (TBD).  Putting notes in READMEs in GitHub is fine as a working area, so it also depends on how the topic hierarchy is crafted/documented in the mauals/regulations.

 To be further discussed at [TT-WISMD 2023-03-08](https://github.com/wmo-im/tt-wismd/wiki/Meeting-2023-03-08).

**Comment by tomkralidis** [comment]
> 

Thanks @josusky.  I'll open a dedicated issue on this front.  We'll also want to review/improve the bundle tooling.

**Review by antje-s — APPROVED** [review]
Should be conform to WMO UNIFIED DATA POLICY - Annex 1 to Resolution 1 (https://library.wmo.int/doc_num.php?explnum_id=11256)

**Comment by amilan17** [comment]
see PR #53

**Pull request closed without merging**
